accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/', views.signup, name='signup'),
    url(r'^login/', views.loginview, name='login'),
]

posts/urls.py
from django.conf.urls import url
from . import views

app_name = 'posts'

urlpatterns = [
    url(r'^create/', views.create, name='create'),
]

redditc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^posts/', include('posts.urls'))

]

posts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=200)
    url = models.TextField()
    pub_date = models.DateTimeField()
    author = models.ForeignKey(User)
    votes_total = models.IntegerField(default=1)
    

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login

# Create your views here.
def signup(request):
    if request.method == 'POST':
        if request.POST['password1'] == request.POST['password2']:
            try:
                User.objects.get(username=request.POST['username'])
                return render(request, 'accounts/signup.html', {'error': 'Username has already been taken'})
            except User.DoesNotExist:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                login(request, user)
                return render(request, 'accounts/signup.html')
            # password2=request.POST['password2']
        else:
            return render(request, 'accounts/signup.html', {'error':'Passwords do not match'})
    else:
        return render(request, 'accounts/signup.html')

def loginview(request):
    if request.method == 'POST':
        user = authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST['next'])

            return render(request, 'accounts/login.html', {'error':'Login Successful!'})
        else:
            return render(request, 'accounts/login.html', {'error':'The Username and password did not match'})
    else:
        return render(request, 'accounts/login.html')

posts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def create(request):
    return render(request, 'posts/create.html')

accounts/templates/accounts/login.html
<h1>Login</h1>

{% if error %}
{{error}}
{% endif %}

<form action="{% url 'accounts:login' %}" method="post">
  {% csrf_token %}

  {% if request.GET.next %}
  <input type="hidden" name="next" value={{ request.GET.next }} />
  {% endif %}
  <p>username</p>
  <input type="text" name="username" value="">
  <br>
  <p>password</p>
  <br>
  <input type="password" name="password" value="">
  <br>
  <input type="submit" name="" value="Login">
</form>

accounts/templates/accounts/signup.html
<h1>Signup</h1>

{% if error %}
{{error}}
{% endif %}

<form action="{% url 'accounts:signup' %}" method="post">
  {% csrf_token %}
  <p>username</p>
  <input type="text" name="username" value="">
  <br>
  <p>password</p>
  <br>
  <input type="password" name="password1" value="">
  <br>
  <input type="password" name="password2" value="">
  <input type="submit" name="" value="Submit">
</form>

posts/templates/posts/create.html
<h1>New Post</h1>

{% if error %}
{{error}}
{% endif %}

<form action="{% url 'posts:create' %}" method="post">
  {% csrf_token %}


  Title:
  <br>
  <input type="text" name="title" value="">
  <br>
  URL:
  <br>
  <input type="password" name="url" value="">
  <br>
  <input type="submit" name="" value="Post">
</form>